name: systemd-netlogd CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: update
      run: sudo apt-get update
    - name: install python
      run: sudo apt-get install python3 python3-pip python3-dev python3-setuptools build-essential python3-sphinx python-sphinx python-configparser
    - name: install build essentials
      run: sudo apt-get install -y ninja-build glib-2.0-dev libudev-dev libyaml-dev libsystemd-dev clang gperf libcap-dev build-essential
    - name: build
      run: make


